"""
Prompt templates for Agent 2 (Campaign Strategy Agent).

Design note:
The original single-state CAMPAIGN_PROMPT (kept below for reference / fallback
use) issues one Gemini call per state, which means 15 calls total for this
project — expensive on free-tier quota and slow.

CAMPAIGN_PROMPT_MULTI_STATE preserves the exact same JSON schema, field
meanings, and instruction style, but accepts a BATCH of states (all from the
same cluster) in a single call, returning one JSON object keyed by state name.
This is what campaign_agent.py uses by default.
"""

# --------------------------------------------------------------------------
# Multi-state (cluster-batched) prompt — used by default for minimum API calls
# --------------------------------------------------------------------------

CAMPAIGN_PROMPT_MULTI_STATE = """
You are the Campaign Strategy Agent for Industry Academy Community (IAC).

Your task is to design a complete outreach and engagement campaign for EACH of the
Indian states listed below. All states in this batch share the same cluster and persona,
but each state has its own specific data — the campaign for each state MUST be distinct
and grounded in that state's own numbers. Do NOT reuse identical wording across states.

You are given the State Intelligence Report (from Agent 1) for each state.
Use ONLY the provided information.

The campaign should focus on increasing awareness, registrations and participation in
IAC's education, skill development and career programmes.

----------------------------------------------------
SHARED CLUSTER CONTEXT
----------------------------------------------------

Cluster:
{cluster}

Persona:
{persona}

Priority:
{priority}

----------------------------------------------------
STATES IN THIS BATCH
----------------------------------------------------

{states_block}

----------------------------------------------------

Design a realistic, distinct campaign for EACH state above.

Return ONLY valid JSON. The JSON format MUST be a single object keyed by state name,
where each state's value follows EXACTLY this schema:

{{
    "<state_name>": {{
        "campaign_summary":"",

        "campaign_objective":"",

        "target_persona":"",

        "campaign_priority":"",

        "communication_channels":[
            ""
        ],

        "campaign_duration":"",

        "communication_frequency":"",

        "campaign_phases":{{
            "phase_1":"",
            "phase_2":"",
            "phase_3":""
        }},

        "marketing_message":"",

        "KPIs":[
            "",
            "",
            ""
        ],

        "expected_outcomes":[
            "",
            "",
            ""
        ]
    }}
}}

Include one such entry for every state listed above, keyed by its exact state name.

Return ONLY JSON.

Do NOT explain.

Do NOT use markdown.

Do NOT include ```json.
"""

# Template for one state's block inside {states_block} above
STATE_BLOCK_TEMPLATE = """
--- STATE: {state} ---

State Profile:
Communication Channels: {channels}
Literacy Rate: {literacy}
Urban Population: {urban}
Population Density: {density}
Youth Population: {youth}
PMKVY Rate: {pmkvy}
Unemployment Rate: {unemployment}

State Intelligence:
Summary: {summary}
Strengths: {strengths}
Challenges: {challenges}
Recommendation: {recommendation}
"""


# --------------------------------------------------------------------------
# Original single-state prompt — kept for reference, and as a fallback for
# re-generating ONE specific state individually (e.g. after a failed batch)
# --------------------------------------------------------------------------

CAMPAIGN_PROMPT_SINGLE_STATE = """
You are the Campaign Strategy Agent for Industry Academy Community (IAC).

Your task is to design a complete outreach and engagement campaign for ONE Indian state.

You are given the State Intelligence Report generated by Agent 1.

Use ONLY the provided information.

The campaign should focus on increasing awareness, registrations and participation in IAC's education, skill development and career programmes.

----------------------------------------------------
STATE PROFILE
----------------------------------------------------

State:
{state}

Cluster:
{cluster}

Persona:
{persona}

Priority:
{priority}

Communication Channels:
{channels}

Literacy Rate:
{literacy}

Urban Population:
{urban}

Population Density:
{density}

Youth Population:
{youth}

PMKVY Rate:
{pmkvy}

Unemployment Rate:
{unemployment}

----------------------------------------------------
STATE INTELLIGENCE
----------------------------------------------------

Summary:
{summary}

Strengths:
{strengths}

Challenges:
{challenges}

Recommendation:
{recommendation}

----------------------------------------------------

Design a realistic campaign.

Return ONLY valid JSON.

The JSON format MUST be:

{{
    "campaign_summary":"",

    "campaign_objective":"",

    "target_persona":"",

    "campaign_priority":"",

    "communication_channels":[
        ""
    ],

    "campaign_duration":"",

    "communication_frequency":"",

    "campaign_phases":{{
        "phase_1":"",
        "phase_2":"",
        "phase_3":""
    }},

    "marketing_message":"",

    "KPIs":[
        "",
        "",
        ""
    ],

    "expected_outcomes":[
        "",
        "",
        ""
    ]
}}

Return ONLY JSON.

Do NOT explain.

Do NOT use markdown.

Do NOT include ```json.
"""